stages:
  - deploy

deploy-job-master:
  stage: deploy
  only:
    - main
  image: docker:latest
  script:
    - docker ps
    - docker system prune -a --volumes -f
    - docker login -u joklem -p $dockerhub_front
    - cd disc-golf-front-react && docker buildx build --progress=plain --force-rm --push -t joklem/discgolf-front:latest .
